### ISSUE TITLE
How to manually create the endpoint registration?

### ISSUE THREAD

**Issue by mayrstefan** [pivotal-cf/docs-metric-registrar#10]
We have trouble using the cf cli plugin to register an endpoint on Windows (https://github.com/pivotal-cf/metric-registrar-cli/issues/4).

I looks like the plugin is not really needed. Because of the issues we had we created the user provided service manually (inspired by the ones created from the plugin). This seems to work. I think this manual approach should also be in the documentation or are we missing an additional step the plugin is doing?

**Comment by mlimonczenko** [comment]
Hello @mayrstefan,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
