### ISSUE TITLE
Can remove the note mentioning "[LGR/] ERR Invalid syslog drain URL: parse failure"

### ISSUE THREAD

**Issue by AkihiroKitada** [pivotal-cf/docs-metric-registrar#16]
According to the following docs regarding Metrics Registrar, it mentions that the benign error message like "[LGR/] ERR Invalid syslog drain URL: parse failure."
https://docs.pivotal.io/platform/application-service/2-7/metric-registrar/using.html#register-endpoint

However, since Pivotal Platform 2.7, Syslog agent has been default with PAS. As a result, the benign error "[LGR/] ERR Invalid syslog drain URL: parse failure" should not be logged any more.

Could we consider to remove the following notes from the docs for Metrics Registrar from Pivotal Platform 2.7?
```
Note: Each metrics endpoint registered with Metric Registrar creates a service instance. If the generated service name is longer than 50 characters, it will be encoded with a hash.
```

**Comment by mlimonczenko** [comment]
Thank you, @AkihiroKitada. I have removed the note.
