### ISSUE TITLE
broken link metric-registrar-examples

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/docs-metric-registrar#4]
hi,
the link to [metric-registrar-examples](https://github.com/pivotal-cf/docs-metric-registrar/blob/2.4/using.html.md.erb#L31) is broken

**Comment by heidmotron** [comment]
@vchrisb - Thanks for letting us know that link was broken. It's now a public repo so should work now.

**Comment by mlimonczenko** [comment]
Hello @vchrisb,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
